// 获取作者信息
export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_SUCCESS = 'AUTHOR_SUCCESS';
export const AUTHOR_FAILUTE = 'AUTHOR_FAILUTE';

// 编辑作者信息
export const SAVE_AUTHOR_REQUEST = 'SAVE_AUTHOR_REQUEST';
export const SAVE_AUTHOR_SUCCESS = 'SAVE_AUTHOR_SUCCESS';
export const SAVE_AUTHOR_FAILUTE = 'SAVE_AUTHOR_FAILUTE';
