// 获取评论
const COMMENTS_REQUEST = 'COMMENTS_REQUEST';
const COMMENTS_SUCCESS = 'COMMENTS_SUCCESS';
const COMMENTS_FAILURE = 'COMMENTS_FAILURE';

// 评论
const SAVE_COMMENT_REQUEST = 'SAVE_COMMENT_REQUEST';
const SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS';
const SAVE_COMMENT_FAILURE = 'SAVE_COMMENT_FAILURE';