// 获取文章列表
export const ARTICLES_REQUEST = 'ARTICLES_REQUEST';
export const ARTICLES_SUCCESS = 'ARTICLES_SUCCESS';
export const ARTICLES_FAILURE = 'ARTICLES_FAILURE';

// 获取作者信息
export const AUTHOR_REQUEST = 'AUTHOR_REQUEST';
export const AUTHOR_SUCCESS = 'AUTHOR_SUCCESS';
export const AUTHOR_FAILUTE = 'AUTHOR_FAILUTE';

// 编辑作者信息
export const SAVE_AUTHOR_REQUEST = 'SAVE_AUTHOR_REQUEST';
export const SAVE_AUTHOR_SUCCESS = 'SAVE_AUTHOR_SUCCESS';
export const SAVE_AUTHOR_FAILUTE = 'SAVE_AUTHOR_FAILUTE';

// 获取文章详情
export const ARTICLE_REQUEST = 'ARTICLE_REQUEST';
export const ARTICLES_SUCCESS = 'ARTICLE_SUCCESS';
export const ARTICLES_FAILURE = 'ARTICLE_FAILURE';

// 新增、编辑文章
export const SAVE_ARTICEL_REQUEST = 'SAVE_ARTICEL_REQUEST';
export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS';
export const SAVE_ARTICLE_FAILUTE = 'SAVE_ARTICLE_FAILUTE';
