// 获取作者信息
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

// 登录后刷新浏览器，从本地获取用户信息添加至state
export const ADD_USER_FROM_LOCAL = 'ADD_USER_FROM_LOCAL';

// 编辑作者信息
export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';

// 修改密码
export const RESET_PASSWD_REQUEST = 'RESET_PASSWD_REQUEST';
export const RESET_PASSWD_SUCCESS = 'RESET_PASSWD_SUCCESS';
export const RESET_PASSWD_FAILURE = 'RESET_PASSWD_FAILURE';